using System.Text.Json;

namespace StructoFox.App;

/// <summary>
/// Tiny localization facade. <c>Loc.S(key)</c> resolves a string: a JSON overlay (Languages/&lt;lang&gt;.json)
/// first, then the built-in table, then English, then the raw key. On startup it exports the built-in
/// English (and German) tables to Languages/*.json so translators have a ready file to edit.
/// </summary>
public static class Loc
{
    // Active UI language code ("en", "de", ...). The fox is bilingual for now; more tongues later.
    public static string Lang { get; set; } = "en";

    // User-editable translations, loaded from Languages/<lang>.json — take priority over the built-ins.
    static Dictionary<string, string> _overlay = new();

    /// <summary>Where the externalised translation files live (next to the app).</summary>
    public static string LangDir => Path.Combine(AppContext.BaseDirectory, "Languages");

    /// <summary>Exports the built-in tables as starter JSON (if missing) and loads the active overlay.
    /// Call once at startup.</summary>
    public static void Init()
    {
        try
        {
            // Active language: the user's saved choice if any, otherwise the OS culture
            // (German system → German UI), otherwise English. This is why everything used to
            // come out English — nothing ever set Lang away from its "en" default.
            var pref = AppSettings.Lang;
            Lang = !string.IsNullOrWhiteSpace(pref) ? pref : DetectCulture();

            Directory.CreateDirectory(LangDir);
            ExportOrSync("en", En);
            ExportOrSync("de", De);
            // Built-in languages always use the in-code table (the exported json is only a translator
            // starter); loading it back as an overlay would let a stale file shadow newer strings.
            _overlay = IsBuiltin(Lang) ? new() : LoadOverlay(Lang);
        }
        catch { /* localization is best-effort; built-ins remain the fallback */ }
    }

    static bool IsBuiltin(string code) => Builtins.Any(b => b.Code == code);

    /// <summary>Switches the active UI language, persists the choice and reloads its overlay. Callers
    /// rebuild their UI afterwards to re-resolve every string.</summary>
    public static void SetLanguage(string code)
    {
        Lang = code;
        AppSettings.Lang = code;
        _overlay = IsBuiltin(code) ? new() : LoadOverlay(code);
    }

    // Maps the OS UI culture to one of our supported language codes (German → "de", else "en").
    static string DetectCulture()
    {
        try { return System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "de" ? "de" : "en"; }
        catch { return "en"; }
    }

    /// <summary>The languages StructoFox ships built-in (code → display name), for the switcher.</summary>
    public static IReadOnlyList<(string Code, string Name)> Builtins { get; } =
        new[] { ("en", "English"), ("de", "Deutsch") };

    // Writes the language table to Languages/<lang>.json as a base for translators, and keeps it in sync: any keys
    // added to the in-code table since the file was created are appended, without touching existing entries. This
    // is safe for the built-in en/de starters (never loaded back as overlays) and ensures new strings reach the
    // packs translators copy from.
    static void ExportOrSync(string lang, Dictionary<string, string> dict)
    {
        var path = Path.Combine(LangDir, lang + ".json");
        var opts = new JsonSerializerOptions { WriteIndented = true };
        if (!File.Exists(path)) { File.WriteAllText(path, JsonSerializer.Serialize(dict, opts)); return; }

        var existing = LoadOverlay(lang);
        var missing = dict.Where(kv => !existing.ContainsKey(kv.Key)).ToList();
        if (missing.Count == 0) return;                 // already up to date

        foreach (var kv in missing) existing[kv.Key] = kv.Value;   // append newcomers, keep translations
        try { File.WriteAllText(path, JsonSerializer.Serialize(existing, opts)); } catch { /* best-effort */ }
    }

    // Reads a Languages/<lang>.json overlay, or an empty map if absent/unreadable.
    static Dictionary<string, string> LoadOverlay(string lang)
    {
        var path = Path.Combine(LangDir, lang + ".json");
        try { return File.Exists(path) ? JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(path)) ?? new() : new(); }
        catch { return new(); }
    }

    // English baseline — the safety net every key falls back to if a translation is missing.
    static readonly Dictionary<string, string> En = new()
    {
        ["App_Title"]    = "StructoFox",
        ["App_Tagline"]  = "Flow · Struct · Code",
        ["Smoke_Header"] = "Core smoke test — C# generated from a sample class:",

        // Home / project browser
        ["Home_NewProject"]    = "➕  New project",
        ["Home_AddLibrary"]    = "📁  Add library",
        ["Home_NewProjectTip"] = "Create a new project — a folder holding its classes, functions, diagrams and boards",
        ["Home_AddLibraryTip"] = "Register a folder that contains several projects — a shelf StructoFox scans",
        ["Home_Recent"]        = "🕘  Recent",
        ["Home_Libraries"]     = "Libraries",
        ["Home_RemoveLibrary"] = "✕  Remove library",
        ["Home_NoProjects"]    = "No projects",
        ["Home_NoProjectsHint"] = "No projects here yet — create one with ➕",
        ["Home_TabProjects"]   = "📁  Projects",

        // Sketchbook (standalone diagrams)
        ["Sketch_Nav"]      = "✏  Sketchbook",
        ["Sketch_NavTip"]   = "Standalone diagrams that belong to no project (in Documents/StructoFox/Sketchbook)",
        ["Sketch_Title"]    = "Sketchbook",
        ["Sketch_NewPap"]   = "＋ 🔁 Flowchart",
        ["Sketch_NewStruct"] = "＋ ▦ Structogram",
        ["Sketch_NewBoard"] = "＋ 🗺 Board",
        ["Sketch_Empty"]    = "No sketches yet — create one above.",
        ["Sketch_NamePrompt"] = "Sketch name:",
        ["Sketch_DeleteConfirm"] = "Delete sketch “{0}”? Its diagram is removed too.",
        ["Sketch_TypeAll"]  = "All",
        ["Sketch_Open"]     = "📂 Open in editor",
        ["Sketch_OpenTip"]  = "Browse the whole sketchbook as a workspace — to clean up classes/objects created on a board",

        // Main (entry point) tab
        ["Main_Blurb"]  = "The program's entry point — its main(). One per project; it gets its own tab so it stays in sight.",
        ["Main_Create"] = "▶ Create main",
        ["Main_Unset"]  = "Unset as main",
        ["Main_SetAs"]  = "▶ Set as main",

        // Cockpit
        ["Cockpit_Exit"]    = "Back",
        ["Cockpit_ExitTip"] = "Back to projects",
        ["Sec_New"]         = "＋ New {0}",
        ["Sec_NewPrompt"]   = "{0} name:",
        // Section type labels (singular for "New …", plural for headings/empties).
        ["SecSg_Boards"] = "Board", ["SecSg_Main"] = "Main", ["SecSg_Namespace"] = "Namespace",
        ["SecSg_Class"] = "Class", ["SecSg_Struct"] = "Struct", ["SecSg_Interface"] = "Interface",
        ["SecSg_Enum"] = "Enum", ["SecSg_Function"] = "Function", ["SecSg_Object"] = "Object", ["SecSg_Export"] = "Export",
        ["SecPl_Boards"] = "Boards", ["SecPl_Main"] = "Main", ["SecPl_Namespace"] = "Namespaces",
        ["SecPl_Class"] = "Classes", ["SecPl_Struct"] = "Structs", ["SecPl_Interface"] = "Interfaces",
        ["SecPl_Enum"] = "Enums", ["SecPl_Function"] = "Functions", ["SecPl_Object"] = "Objects", ["SecPl_Export"] = "Export",
        ["Sec_FilterName"]  = "Filter by name…",
        ["Sec_FilterSortTip"] = "Filter by name & sort",
        ["Sec_NsAll"]       = "(all namespaces)",
        ["Sec_NsNone"]      = "(no namespace)",
        ["Sec_SetNs"]       = "🏷 Set namespace…",
        ["Sec_NsPrompt"]    = "Namespace (empty = none):",
        ["Sec_DupMsg"]      = "A {0} named “{1}” already exists in this namespace. Create another one anyway?",
        ["Sec_DupTitle"]    = "Name already exists",
        ["Board_CrossDupMsg"] = "Already exists in this project: {0}. Delete or rename it first, then paste again.",
        ["Usage_BaseClass"]  = "base class",
        ["Usage_Interface"]  = "interface",
        ["Usage_InstanceOf"] = "instance of",
        ["Usage_Namespace"]  = "namespace",
        ["Usage_Board"]      = "board",
        ["Usage_Subroutine"] = "subroutine",
        ["Usage_FieldType"]  = "type",
        ["Link_Title"]        = "Still in use",
        ["Link_UsedByRename"] = "Still used by:\n{0}\n\nWhat should happen to those links?",
        ["Link_ActionRename"] = "Rename the links too",
        ["Link_ActionLeave"]  = "Leave the links (they'll point nowhere)",
        ["Link_ActionDelete"] = "Delete the links",
        ["Link_UsedByDelete"] = "Still used by:{0}\n\nThose links will be cleared.",
        ["Sec_Empty"]       = "No {0} yet.",
        ["Sec_Delete"]      = "✕  Delete",
        ["Sec_DeleteTitle"]    = "Delete",
        ["Sec_DeleteConfirm1"] = "Delete “{0}”? Everything attached to it (members, diagrams) goes too.",
        ["Sec_DeleteConfirmN"] = "Delete {0} selected entities? Everything attached to them goes too.",
        ["Sec_DeleteBoardWarn"] = "Note: board(s) are assigned to this ({0}). They are NOT deleted — remove them manually in the Boards tab.",
        ["Sec_BoardsBlurb"] = "Structure boards — arrange entities on a canvas. (Board canvas port coming.)",
        ["Sec_ExportBlurb"] = "Generate source from your structures in 10 languages. (Wiring coming.)",

        // New-project dialog
        ["NewProj_Title"]     = "New project",
        ["NewProj_Name"]      = "Project name:",
        ["NewProj_Syntax"]    = "Code syntax (autocomplete):",
        ["Syntax_Title"]      = "Code syntax",
        ["Syntax_Intro"]      = "Pick the code language for this project's node-editor autocomplete (method signatures are shown in this syntax). You can change it later in the diagram toolbar.",
        ["NewProj_NoLib"]     = "No project library yet. Choose a folder where your projects will live:",
        ["NewProj_ChooseLib"] = "Create the project in:",
        ["NewProj_Browse"]    = "Browse…",
        ["NewProj_FreeFmt"]   = "{0} MB free on {1}",
        ["NewProj_ExistsTitle"] = "Name already exists",
        ["NewProj_ExistsMsg"]   = "A project “{0}” already exists in this library.\n\nYes = open it,  No = choose another name,  Cancel = abort.",
        ["Common_OK"]         = "OK",
        ["Common_Cancel"]     = "Cancel",
        ["Common_Yes"]        = "Yes",
        ["Common_No"]         = "No",
        ["Common_DontShowAgain"] = "Don't show this again",

        // Diagram chooser (DiagramLauncher)
        ["Diag_Title"]     = "Diagram",
        ["Diag_SketchOf"]  = "Sketch the flow of:\n{0}",
        ["Diag_Pap"]       = "🔁 Programmablaufplan",
        ["Diag_PapExists"] = "🔁 Programmablaufplan (exists)",
        ["Diag_Ns"]        = "▦ Structogram",
        ["Diag_NsExists"]  = "▦ Structogram (exists)",
        ["Diag_NsTip"]     = "Nassi-Shneiderman structogram editor (DIN 66261)",
        ["Diag_Board"]     = "🗺 Board",

        // Common
        ["Common_Untitled"] = "Untitled",
        ["Flow_EditText"]   = "✎ Edit text…",

        // Structogram editor
        ["Struct_Title"]          = "▦  Structogram — {0}",
        ["Struct_Hint"]           = "Right-click any block to edit / insert / wrap. Use ＋ to add.",
        ["Struct_CodeExport"]     = "⇩ Code skeleton",
        ["Struct_CodeExportTip"]  = "Send this structogram's function/method to the code exporter (frame only, no AI).",
        ["Struct_CodeNoEntity"]   = "This structogram isn't tied to a project function or method, so there's no code skeleton to export.",
        ["Struct_PhStatement"]    = "(statement)",
        ["Struct_PhCondition"]    = "(condition)",
        ["Struct_True"]           = "true",
        ["Struct_False"]          = "false",
        ["Struct_PhWhile"]        = "while (…)",
        ["Struct_PhDoWhile"]      = "do … while (…)",
        ["Struct_KwWhile"]        = "while",
        ["Struct_KwDoWhile"]      = "do … while",
        ["Struct_PhSelector"]     = "(selector)",
        ["Struct_Case"]           = "case",
        ["Struct_InsertAbove"]    = "Insert above",
        ["Struct_InsertBelow"]    = "Insert below",
        ["Struct_AddLoopBody"]    = "Add to loop body",
        ["Struct_AddTrue"]        = "Add to TRUE branch",
        ["Struct_AddFalse"]       = "Add to FALSE branch",
        ["Struct_AddArm"]         = "Add case arm",
        ["Struct_DeleteBlock"]    = "✕ Delete block",
        ["Struct_KStatement"]     = "Statement",
        ["Struct_KIf"]            = "If / Else",
        ["Struct_KWhile"]         = "While loop (pre-test)",
        ["Struct_KDoWhile"]       = "Do-While loop (post-test)",
        ["Struct_KCase"]          = "Case (multi-way)",
        ["Struct_KSubroutine"]    = "Subroutine (links to a diagram)",
        ["Struct_PhSubroutine"]   = "(subprogram)",
        ["Struct_DefSubroutine"]  = "subprogram",
        ["Struct_KJump"]          = "Exit (return / break / continue)",
        ["Struct_DefJump"]        = "return",
        ["Struct_ShowChart"]      = "🗺 Show chart…",
        ["Struct_ShowChartTip"]   = "Double-click to open this subprogram's diagram",
        ["Sub_NamePrompt"]        = "Subprogram (function) name:",
        ["Sub_LinkTitle"]         = "Link subprogram",
        ["Sub_Namespace"]         = "Namespace (to pick from / create in):",
        ["Sub_CallForm"]          = "Call (optional):",
        ["Sub_ReturnLabel"]       = "Return into:",
        ["Sub_ArgsLabel"]         = "Arguments:",
        ["Sub_AssignHint"]        = "variable (e.g. result)",
        ["Sub_ArgsHint"]          = "arguments (e.g. x, y)",
        ["Sub_Instance"]          = "Object to call the method on (it's not static):",
        ["Sub_InstanceHint"]      = "instance (e.g. myObject)",
        ["Sub_NewObject"]         = "＋ New object…",
        ["Sub_Link"]              = "🔗 Link subprogram…",
        ["Sub_Relink"]            = "Re-link (change target)…",
        ["Sub_PickExisting"]      = "Pick an existing function",
        ["Sub_CreateNew"]         = "Create a new function:",
        ["Sub_DuplicateTitle"]    = "Function already exists",
        ["Sub_DuplicateMsg"]      = "A function with this name already exists in this namespace.\n\nYes = use the existing one,  No = create another anyway,  Cancel = go back.",
        ["Sub_RemoveInfo"]        = "The subprogram stays in the Functions library — only this block/node was removed. To delete it for good, remove it in the Functions tab.",
        ["Struct_AddBlockTip"]    = "Add a block",
        ["Struct_AddInline"]      = "＋ add",
        ["Struct_PromptStatement"] = "Statement",
        ["Struct_PromptCondition"] = "Condition / expression",
        ["Struct_PromptCaseLabel"] = "Case label",
        ["Struct_DefCondition"]   = "condition",
        ["Struct_DefWhile"]       = "while (condition)",
        ["Struct_DefDoWhile"]     = "do … while (condition)",
        ["Struct_DefSelector"]    = "selector",
        ["Struct_DefStatement"]   = "statement",
        ["Struct_FlaggedTip"]     = "This region could not be structured from the flowchart — review and rewrite it manually.",

        // Flowchart (PAP) editor
        ["Common_ResetZoomTip"]        = "Reset zoom",
        ["Flow_Title"]                 = "🔁  Flow — {0}",
        ["Flow_Start"]                 = "⬭ Start",
        ["Flow_OnlyOneStart"]          = "A flowchart can have only one Start — it maps to a single function. To draw another procedure, give it its own function/diagram.",
        ["Flow_Process"]               = "▭ Process",
        ["Flow_Decision"]              = "◇ Decision",
        ["Flow_MultiDecision"]         = "◇ Multi-branch (switch/case)",
        ["Flow_CombDir"]               = "Comb direction",
        ["Flow_CombBottom"]            = "Below (tines drop down)",
        ["Flow_CombRight"]             = "Right (tines run right)",
        ["Flow_CombBoth"]              = "Both",
        ["Flow_TineSpacing"]           = "Tine spacing (grid steps)",
        ["Flow_AddTine"]               = "Add case (tine)",
        ["Flow_RemoveTine"]            = "Remove case (tine)",
        ["Flow_ResetStem"]             = "Reset stem",
        ["Flow_CaseDefault"]           = "case",
        ["Flow_CaseLabelDup"]          = "Each case needs a unique, non-empty label.",
        ["Flow_IO"]                    = "▱ I/O",
        ["Flow_Subroutine"]            = "⊟ Subroutine",
        ["Flow_End"]                   = "⬭ End",
        ["Flow_Note"]                  = "✎ Text",
        ["Flow_Annotation"]            = "⌐ Annotation",
        ["Flow_MirrorAnnotation"]      = "Mirror (left/right)",
        ["Flow_Connector"]             = "◯ Connector",
        ["Flow_DefConnector"]          = "A",
        ["Flow_Junction"]              = "• Junction",
        ["Flow_AddNodeTip"]            = "Add a {0} node",
        ["Flow_Select"]                = "🖐",
        ["Flow_SelectTip"]             = "Normal mode: select and drag nodes (drag empty canvas = rubber-band select; right-drag = pan)",
        ["Flow_Scale"]                 = "⤢",
        ["Flow_ScaleTip"]              = "Resize mode: drag the handles on a symbol to scale it (down to its standard size)",
        ["Flow_Connect"]               = "→ Connect",
        ["Flow_ConnectTip"]            = "Click a node, then another, to draw an arrow",
        ["Flow_View"]                  = "⚙ Options ▾",
        ["Flow_ZoomTip"]               = "Zoom — presets or enter a value",
        ["Flow_ZoomManual"]            = "e.g. 130",
        ["Flow_ViewTip"]               = "Options: colours, decoration, zoom, grid",
        ["Flow_LangLabel"]             = "Syntax:",
        ["Flow_LangTip"]               = "Code language for the node-editor autocomplete (method signatures are shown in this syntax) — project-wide setting.",
        ["View_Crop"]                  = "Crop canvas",
        ["View_CropTip"]               = "Trim the canvas to the content, removing empty top/left space",
        ["Grid_Header"]                = "Grid",
        ["Grid_Show"]                  = "Show grid",
        ["Grid_Snap"]                  = "Snap to grid",
        ["Grid_Lines"]                 = "Lines",
        ["Grid_Dashed"]                = "Dashed",
        ["Grid_Dots"]                  = "Dots",
        ["Grid_Color"]                 = "🎨 Grid colour…",
        ["Grid_Opacity"]               = "Grid opacity",
        ["Flow_Remove"]                = "🗑",
        ["Flow_RemoveTip"]             = "Click a node or arrow to delete it",
        ["Flow_DefStart"]              = "Start",
        ["Flow_DefEnd"]                = "End",
        ["Flow_DefDecision"]           = "condition?",
        ["Flow_DefIO"]                 = "input / output",
        ["Flow_DefCall"]               = "call …",
        ["Flow_DefNote"]               = "text",
        ["Flow_DefAnnotation"]         = "annotation",
        ["Flow_DefStep"]               = "step",
        ["Flow_DeleteNode"]            = "✕ Delete node",
        ["Flow_NodeTextPrompt"]        = "Node text",
        ["Flow_BranchPrompt"]          = "Branch label (e.g. yes / no)",
        ["Flow_ArrowPrompt"]           = "Arrow label",
        ["Flow_EditLabel"]             = "✎ Edit label…",
        ["Flow_DeleteArrow"]           = "✕ Delete arrow",
        ["Flow_FlipArrow"]             = "⇄ Flip arrow direction",
        ["Flow_StyleLine"]             = "─ Style: line (no arrowhead)",
        ["Flow_StyleArrow"]            = "➤ Style: arrow",
        ["Flow_Crossover"]             = "Crossover bridges (non-DIN)",
        ["Flow_CrossoverHint"]         = "Non-standard: this is only a temporary visual marker. It is not saved and won't be shown the next time this flowchart is loaded.",
        ["Flow_ResetRoute"]            = "↺ Reset routing",
        ["Flow_DetachJunction"]        = "⊘ Lift out of line",
        ["Flow_Transmission"]          = "⚡ Make transmission path",
        ["Flow_TransmissionOff"]       = "⚡ Back to normal flow line",
        ["Flow_ToStructogramTip"]      = "Convert this flowchart to a structogram",
        ["Flow_ToStructogramTitle"]    = "Convert to structogram",
        ["Flow_ToStructogramOverwrite"] = "A structogram already exists for this function. Overwrite it with the converted flowchart?",
        ["Flow_ToStructogramExists"]    = "A structogram already exists for this flowchart. Overwrite it, or open the existing one?",
        ["Flow_ToStructogramOpen"]      = "Open existing",
        ["Flow_ToStructogramOverwriteBtn"] = "Overwrite",
        ["Flow_ToStructogramPartial"]  = "Some parts of the flowchart can't be expressed as a structogram (e.g. arbitrary jumps / loops). The nodes to fix are marked orange in the flowchart. Restructure them, then convert again.",
        ["Flow_ToStructogramNodeTip"]  = "This node could not be structured into a structogram — restructure the flow here.",
        ["Flow_Background"]            = "🎨 Background colour…",
        ["Flow_ArrowColor"]            = "🎨 Arrow colour…",
        ["Flow_Colors"]                = "Colours",
        ["Flow_LinesOrtho"]           = "⌐ Lines: orthogonal",
        ["Flow_LinesDiagonal"]        = "⟍ Lines: diagonal",
        ["Flow_LinesTip"]             = "Switch between DIN orthogonal flow lines and direct diagonal arrows",
        ["Flow_Symbol"]               = "DIN symbol",
        ["Flow_SymAuto"]              = "▱ Default (input/output)",
        ["Flow_SymDocument"]          = "📄 Document (printout)",
        ["Flow_SymDisplay"]           = "🖥 Display",
        ["Flow_SymManualInput"]       = "⌨ Manual input",
        ["Flow_SymPunchedCard"]       = "🗒 Punched card",
        ["Flow_SymMagneticTape"]      = "🎞 Magnetic tape",
        ["Flow_SymMagneticDisk"]      = "🛢 Magnetic disk / database",
        ["Flow_SymStoredData"]        = "🗄 Stored data",
        ["Flow_SymOffPage"]           = "⬠ Off-page connector (next page)",
        ["Flow_PageWord"]             = "Page",
        ["Flow_PageOf"]               = "Page {0}/{1}",
        ["Flow_PagePrev"]             = "Previous page",
        ["Flow_PageNext"]             = "Next page",
        ["Flow_EntryReadOnly"]        = "This is the entry on the next page — its label mirrors the off-page connector and can't be edited here. Double-click the connector on the first page to change it.",
        ["Flow_OffPageDup"]           = "That off-page connector label is already used. Each one must be unique.",
        ["Flow_SymPreparation"]       = "⬡ Preparation (setup / loop init)",
        ["Flow_SymManualOperation"]   = "⏢ Manual operation",
        ["Flow_SymLoopLimit"]         = "⌂ Loop limit",
        ["Flow_SymDelay"]             = "⏱ Delay",
        ["Flow_SymParallel"]          = "‖ Parallel mode",
        ["Flow_SymSort"]              = "⬙ Sort",
        ["Flow_SymMerge"]             = "▽ Merge",
        ["Flow_SymExtract"]           = "△ Extract",
        ["Flow_SymCollate"]           = "⧖ Collate",
        ["Flow_SymCloud"]             = "☁ Cloud storage",
        ["Flow_CatData"]              = "⛁ Data",
        ["Flow_ExtOff"]               = "(extended ISO symbols off)",
        ["Flow_ExtIso"]               = "Extended ISO symbols",
        ["Flow_ExtOutsideSet"]        = "Outside the chosen symbol set (still ISO 5807)",
        ["Flow_CatStartEnd"]          = "⬭ Start / End",
        ["Flow_CatProcess"]           = "▭ Process",
        ["Flow_CatIO"]                = "▱ I/O",
        ["Flow_CatConnect"]           = "🔗 Connect",
        ["Flow_CatTip"]               = "Hover to choose a variant",
        ["Flow_ArrowDin"]             = "➜ Arrow (DIN, orthogonal)",
        ["Flow_ArrowFree"]            = "⟍ Arrow (free, diagonal)",
        ["NodeTxt_Title"]              = "Node text",
        ["NodeTxt_Font"]               = "Font",
        ["NodeTxt_Size"]               = "Size",
        ["NodeTxt_Bold"]               = "Bold",
        ["NodeTxt_Italic"]             = "Italic",
        ["NodeTxt_Underline"]          = "Underline",
        ["NodeTxt_Strike"]             = "Strikethrough",

        // Diagram decoration (title / watermark / logo)
        ["Decor_Title"]      = "Header",
        ["Decor_Open"]       = "🏷 Header…",
        ["Decor_OpenTip"]    = "Title, info field, watermark and logo on the plan",
        ["Decor_TitleText"]  = "Title:",
        ["Decor_ShowTitle"]  = "Show the title on the plan",
        ["Decor_TitlePos"]   = "Position:",
        ["Decor_TitleSize"]  = "Size:",
        ["Decor_TitleBold"]  = "Bold",
        ["Decor_TitleColor"] = "Title colour",
        ["Decor_TitleEditTip"] = "Right-click: edit title properties",
        ["Decor_WmAngle"]    = "Watermark angle (°):",
        ["Decor_Watermark"]  = "Watermark (faint diagonal text):",
        ["Decor_WatermarkImg"] = "Watermark image (faint, centred):",
        ["Decor_Logo"]       = "Logo image:",
        ["Decor_Browse"]     = "Browse…",
        ["Decor_ClearLogo"]  = "Clear",
        ["Decor_FromPap"]    = "⤵ Get header from the flowchart",
        ["Decor_SaveTemplate"]   = "💾 Save as template…",
        ["Decor_ApplyTemplate"]  = "📋 Apply template…",
        ["Decor_DeleteTemplate"] = "Delete",
        ["Decor_TemplateName"]   = "Template name:",
        ["Decor_TemplateExists"] = "A template “{0}” already exists.\n\nOverwrite it?",
        ["Decor_TemplatePick"]   = "Header templates",

        // Print / Export composer
        ["Common_Ok"]            = "OK",
        ["Pc_GridBtn"]           = "▦ Grid ▾",
        ["Pc_GridShow"]          = "Show grid",
        ["Pc_GridSnap"]          = "Snap to grid",
        ["Pc_GridSpacing"]       = "Spacing",
        ["Pc_GridColor"]         = "Color",
        ["Pc_GridOpacity"]       = "Opacity (%)",
        ["Pc_GridWidth"]         = "Line width",
        ["Pc_GridStyle"]         = "Line style",
        ["Pc_StyleSolid"]        = "Solid",
        ["Pc_StyleDotted"]       = "Dotted",
        ["Pc_StyleDashed"]       = "Dashed",
        ["Pc_StyleCrosses"]      = "Crosses",
        ["Pc_StyleCrossesDots"]  = "Crosses + dots",
        ["Pc_StyleCrossesDashes"]= "Crosses + dashes",
        ["Pc_TextBox"]           = "Text box",
        ["Pc_Label"]             = "Label",
        ["Pc_Size"]              = "Size",
        ["Pc_ColorText"]         = "Text",
        ["Pc_Background"]        = "Background",
        ["Pc_Border"]            = "Border",
        ["Pc_BorderWidth"]       = "Border width",
        ["Pc_Editor"]            = "Editor",
        ["Pc_Align"]             = "Align",
        ["Pc_AlignLeft"]         = "Left",
        ["Pc_AlignCenter"]       = "Center",
        ["Pc_AlignRight"]        = "Right",
        ["Pc_Default"]           = "(default)",
        ["Pc_ListHint"]          = "List: type  1. / a) / - / *  before a line — indent sub-levels with leading spaces.",
        ["Pc_Preview"]           = "Preview",
        ["Pc_LineSpacing"]       = "Line spacing",
        ["Pc_Marker"]            = "Highlight",
        ["Pc_ApplySize"]         = "Size ↵",
        ["Pc_SelSize"]           = "Font size of the selection",
        ["Pc_ClearFormat"]       = "Clear formatting of the selection",
        ["Pc_FormatHelp"]        = "Formatting — select text, then apply:  B bold · I italic · U underline · S strikethrough · x² superscript · x₂ subscript · A text colour · ▨ highlight · Size sets a per-selection font size · ⊘ clears formatting.\nLists: type  1. / a) / - / *  at the start of a line; indent sub-levels with leading spaces.\nFont FAMILY, alignment and line spacing apply to the whole box.",
        ["Pc_AddText"]           = "＋ Text ▾",
        ["Pc_LabelSingle"]       = "Label (single line)",
        ["Pc_TextMulti"]         = "Text box (multi-line)",
        ["Pc_AddHeader"]         = "＋ Header",
        ["Pc_MenuFile"]          = "📁 File ▾",
        ["Pc_MenuOptions"]       = "⚙ Options ▾",
        ["Pc_Save"]              = "💾 Save",
        ["Pc_Load"]              = "Load…",
        ["Pc_NewDoc"]            = "New document",
        ["Pc_Rename"]            = "Rename…",
        ["Pc_SaveAs"]            = "Save as…",
        ["Pc_OverwriteConfirm"]  = "A document “{0}” already exists.\n\nOverwrite it?",
        ["Pc_PaperFormat"]       = "Paper format…",
        ["Pc_GridSettings"]      = "Grid…",
        ["Pc_InsertHeader"]      = "Header",
        ["Pc_Paper"]             = "Paper",
        ["Pc_Orientation"]       = "Orientation",
        ["Pc_Portrait"]          = "Portrait",
        ["Pc_Landscape"]         = "Landscape",
        ["Pc_Name"]              = "Name",
        ["Pc_LoadTitle"]         = "Load document",
        ["Pc_NoSaved"]           = "No saved documents yet.",
        ["Pc_Delete"]            = "Delete",
        ["Pc_DeleteConfirm"]     = "Delete “{0}”?",
        ["Pc_OpenFolder"]        = "📁 Open folder",
        ["Pc_Margins"]           = "Margins (cm)",
        ["Pc_MTop"]              = "Top",
        ["Pc_MBottom"]           = "Bottom",
        ["Pc_MLeft"]             = "Left",
        ["Pc_MRight"]            = "Right",
        ["Pc_HeaderWidth"]       = "Header width…",
        ["Pc_HeaderWidthTitle"]  = "Header max width",
        ["Pc_WidthCm"]           = "Max width (cm)",
        ["Pc_ToDefault"]         = "To default",
        ["Pc_ShowPageNumber"]    = "Show page number",
        ["Pc_ExportPng"]         = "Export…",
        ["Pc_ExportTitle"]       = "Export",
        ["Pc_ExportDpi"]         = "Resolution (DPI)",
        ["Pc_ExportFormat"]      = "Format",
        ["Pc_FmtPngPages"]       = "PNG (one file per page)",
        ["Pc_FmtTiffPages"]      = "TIFF (one file per page)",
        ["Pc_FmtTiffMulti"]      = "TIFF (multipage)",
        ["Pc_FmtPdf"]            = "PDF",
        ["ImgExport_Menu"]       = "🖼 Export as image…",
        ["ImgExport_Tip"]        = "Export this diagram (as shown) as a single image (PNG/JPG/BMP/TIFF).",
        ["ImgExport_Title"]      = "Export image",
        ["ImgExport_Empty"]      = "Nothing to export yet.",
        ["Pc_Exported"]          = "Exported {0} page(s)",
        ["Pc_ExportFailed"]      = "Export failed:",
        ["Pc_Saved"]             = "Saved",
        ["Pc_Edit"]              = "Edit…",
        ["Pc_Bigger"]            = "Bigger",
        ["Pc_Smaller"]           = "Smaller",
        ["Pc_ScaleDots"]         = "Scale…",
        ["Pc_ResetSize"]         = "Reset size (100%)",
        ["Pc_Update"]            = "Update",
        ["Pc_EditSource"]        = "Edit source",
        ["Pc_Delete"]            = "Delete",
        ["Pc_ScalePrompt"]       = "Scale (%) — 100 = original",
        ["Pc_ScaleTitle"]        = "Scale",
        ["Pc_NoDiagrams"]        = "No diagrams found — draw a flowchart first",
        ["Pc_AddDiagramTitle"]   = "Add diagram",
        ["Pc_HeaderEmpty"]       = "Header is empty — enable title, info or a logo",
        ["Pc_NothingToRender"]   = "(nothing to render)",
        ["Menu_DefaultHeader"]   = "🏷 Default header…",
        ["Menu_UserInfo"]        = "👤 User details…",
        ["Menu_Backup"]          = "💾 Backup…",
        ["Backup_Title"]         = "Project backup",
        ["Backup_Folder"]        = "Backup folder (each project gets its own subfolder):",
        ["Backup_Browse"]        = "Browse…",
        ["Backup_PickFolder"]    = "Choose the backup folder",
        ["Backup_OnClose"]       = "Automatically back up when a project is closed",
        ["Backup_Keep"]          = "Number of backups kept per project:",
        ["Backup_Note"]          = "On close, if the project changed since the last backup, a .zip of the whole project is written to <backup folder>/<project>/. Only the newest N zips are kept — older ones are deleted.",
        ["Backup_ErrTitle"]      = "Backup",
        ["Backup_ErrIsProject"]  = "That folder is a StructoFox project. Please choose a backup folder that is NOT a project (and not inside one) — otherwise backups can't be made.",
        ["Backup_ErrInside"]     = "The backup folder is inside the project being backed up, so no backup was made. Please choose a backup folder outside the project.",
        ["Backup_ErrFailed"]     = "The backup could not be written to:\n{0}\n\nPlease check the folder exists and is writable.",
        ["UserInfo_Title"]       = "User details",
        ["UserInfo_Name"]        = "Name (suggested as the header's author):",
        ["UserInfo_Dept"]        = "Department (suggested in the header):",
        ["Decor_Today"]          = "Today",
        ["DefHdr_Title"]         = "Default header for new diagrams",
        ["DefHdr_Pap"]           = "New flowcharts (PAP):",
        ["DefHdr_Struct"]        = "New structograms:",
        ["DefHdr_None"]          = "(none)",
        ["Decor_Corner"]     = "Logo position:",
        ["Decor_LogoWidth"]  = "Logo width:",
        ["Decor_InfoSection"]  = "Info field (title block)",
        ["Decor_ShowInfo"]     = "Show the info field on the plan",
        ["Decor_ShowPage"]     = "Show page number (auto, in the info field)",
        ["Decor_InfoPos"]      = "Info position:",
        ["Decor_InfoName"]     = "Name:",
        ["Decor_InfoProject"]  = "Project:",
        ["Decor_InfoProjectNo"]= "Project no.:",
        ["Decor_InfoVersion"]  = "Version:",
        ["Decor_InfoDate"]     = "Date:",
        ["Decor_InfoAuthor"]   = "Author:",
        ["Decor_InfoDept"]     = "Department:",
        ["Decor_InfoExtra"]    = "Note:",
        ["Decor_InfoPage"]     = "Page:",

        // Per-element styling
        ["Style_Menu"]      = "🎨 Style",
        ["Style_Line"]      = "Line colour",
        ["Style_Fill"]      = "Fill colour",
        ["Style_Text"]      = "Text colour",
        ["Style_Thickness"] = "Line thickness",
        ["Style_Reset"]     = "Reset style",
        ["Style_Inherit"]   = "Inherit (default)",
        ["Style_Open"]      = "🎨 Style…",
        ["Palette_Choose"]  = "Choose palette",
        ["Pal_Title"]         = "🎨 Palette editor",
        ["Pal_Label"]         = "Palette:",
        ["Pal_New"]           = "New…",
        ["Pal_NewTip"]        = "Create a new palette",
        ["Pal_Save"]          = "💾 Save",
        ["Pal_SaveTip"]       = "Save this palette to a file",
        ["Pal_AddUpdate"]     = "＋ Add / Update",
        ["Pal_AddUpdateTip"]  = "Add a new colour, or update the selected one",
        ["Pal_Remove"]        = "✕ Remove",
        ["Pal_RemoveTip"]     = "Remove the selected colour",
        ["Pal_Name"]          = "Name:",
        ["Pal_ColorName"]     = "Colour name",
        ["Pal_DefaultColor"]  = "Colour",
        ["Pal_NewPrompt"]     = "New palette name:",
        ["Pal_NewDefault"]    = "My Palette",
        ["Pal_NewTitle"]      = "New palette",
        ["Pal_Saved"]         = "Saved palette \"{0}\" to:\n{1}",
        ["Pal_SavedTitle"]    = "Palette saved",

        // Style editor window
        ["StyleEd_Title"]     = "🎨 Element style",
        ["StyleEd_Preset"]    = "Preset slot:",
        ["StyleEd_Apply"]     = "Apply",
        ["StyleEd_SaveSlot"]  = "💾 Save as slot…",
        ["StyleEd_Line"]      = "Line colour",
        ["StyleEd_Fill"]      = "Fill colour",
        ["StyleEd_Text"]      = "Text colour",
        ["StyleEd_Thickness"] = "Line thickness",
        ["StyleEd_Preview"]   = "Preview",
        ["StyleEd_Sample"]    = "Sample text",
        ["StyleEd_SlotName"]  = "Slot name:",
        ["Common_OK"]         = "OK",
        ["Common_Cancel"]     = "Cancel",

        // Entity editor dialog
        ["Common_Name"]            = "Name",
        ["Common_None"]            = "(none)",
        ["Common_Save"]            = "Save",
        ["Common_AddPlus"]         = "＋ Add",
        ["CodeEdit_Title"]         = "Edit {0}",
        ["CodeEdit_Type"]          = "Type",
        ["CodeEdit_Namespace"]     = "Namespace",
        ["CodeEdit_ParentNamespace"] = "Parent namespace",
        ["CodeEdit_Description"]   = "Description",
        ["CodeEdit_Inherits"]      = "Inherits from",
        ["CodeEdit_Implements"]    = "Implements",
        ["CodeEdit_NoInterfaces"]  = "(no interfaces defined yet)",
        ["CodeEdit_InstanceOf"]    = "Instance of",
        ["CodeEdit_ObjectUsage"]   = "Usage (scanned from diagrams)",
        ["CodeEdit_ObjCreated"]    = "Created in:",
        ["CodeEdit_ObjDestroyed"]  = "Destroyed in:",
        ["CodeEdit_ObjUsed"]       = "Used in:",
        ["CodeEdit_Methods"]       = "Methods",
        ["CodeEdit_Fields"]        = "Fields",
        ["CodeEdit_EnumValues"]    = "Enum values",
        ["CodeEdit_DataPorts"]     = "Data ports",
        ["CodeEdit_DeclaredVars"]  = "Declared variables",
        ["CodeEdit_LoopVars"]      = "Loop variables",
        ["CodeEdit_VarsHint"]      = "No variables declared. Note them in the diagram as a step, e.g.  int total = 0",
        ["CodeEdit_ConstructorLbl"]= "constructor",
        ["CodeEdit_DestructorLbl"] = "destructor",
        ["CodeEdit_MethodFlowTip"] = "Sketch this method's flow / structogram",
        ["CodeEdit_AddParam"]      = "＋ param",
        ["CodeEdit_AddMethod"]     = "Method",
        ["CodeEdit_AddConstructor"]= "Constructor",
        ["CodeEdit_AddDestructor"] = "Destructor",
        ["CodeEdit_AddGetter"]     = "Add getter (Get…)",
        ["CodeEdit_AddSetter"]     = "Add setter (Set…)",
        ["CodeEdit_DefaultValue"]  = "Value",
        ["CodeEdit_Delete"]        = "✕  Delete",
        ["CodeEdit_DeleteConfirm"] = "Delete “{0}”? Anything attached to it (parameters, diagrams, …) goes with it.",
        ["CodeEdit_DeleteTitle"]   = "Delete",
        ["CodeEdit_DeleteBoardWarn"] = "A board is assigned to this method ({0}). It is NOT deleted — remove it manually in the Boards tab.",
        ["Common_NameColon"]       = "Name:",
        ["Common_Add"]             = "Add",

        // Boards gallery (cockpit Boards section)
        ["Boards_New"]        = "＋ New board",
        ["Boards_NewPrompt"]  = "Board name:",
        ["Boards_Default"]    = "Board",
        ["Boards_Empty"]      = "No boards yet — create one with ＋.",
        ["Boards_Open"]       = "Open",
        ["Boards_Rename"]     = "✎ Rename…",
        ["Boards_Delete"]     = "✕  Delete board",
        ["Boards_DeleteConfirm"] = "Delete the board \"{0}\"? (Entities stay; only this board's layout is removed.)",
        ["Boards_DeleteTitle"]   = "Delete board",

        // Code board canvas
        ["Code_AddToBoard"]       = "＋ Add",
        ["Code_AddToBoardTip"]    = "Add a new or existing entity to this board",
        ["Code_AllTypes"]         = "(all types)",
        ["Code_SelectMode"]       = "✋ Select / move",
        ["Code_SelectModeTip"]    = "Select & move cards: drag empty space to box-select, right-drag to pan, Ctrl-click to add/remove, Ctrl+A all, Delete removes",
        ["Code_ConnectPorts"]     = "→ Connect ports",
        ["Code_ConnectPortsTip"]  = "Click an output port, then a matching input port, to wire them",
        ["Code_ScaleCards"]       = "⤢ Resize",
        ["Code_ScaleCardsTip"]    = "Resize mode: drag the handles on a card to scale it (down to its natural size)",
        ["Code_RemoveCards"]      = "✕ Remove from board",
        ["Code_RemoveCardsTip"]   = "Remove the selected cards from this board (entities are kept)",
        ["Code_ExportAll"]        = "⇩ Export all",
        ["Code_ExportAllTip"]     = "Generate source for every entity on this board",
        ["Code_ExportSelected"]   = "⇩ Export selected",
        ["Code_ExportSelectedTip"]= "Generate source for the selected entities",
        ["Code_NoSelection"]      = "Nothing selected.",
        ["Code_ConnStartOutput"]  = "Start a connection at an output port (right side).",
        ["Code_ConnEndInput"]     = "Finish a connection at an input port (left side).",
        ["Code_ConnTitle"]        = "Connect ports",
        ["Code_MismatchConv"]     = "Passing convention mismatch: {0} is {1} but {2} is {3}.",
        ["Code_MismatchType"]     = "Type mismatch: {0} is {1} but {2} is {3}.",
        ["Code_MismatchTitle"]    = "Cannot connect",
        ["Code_AddType"]          = "Add {0}…",
        ["Code_Edit"]             = "✎ Edit…",
        ["Code_SketchFlow"]       = "🔁 Sketch flow…",
        ["Code_ExportThis"]       = "⇩ Export this",
        ["Code_SwitchVertical"]   = "Ports: switch to vertical",
        ["Code_SwitchHorizontal"] = "Ports: switch to horizontal",
        ["Code_RemoveFromBoard"]  = "Remove from board",
        ["Board_RemoveInfo"]      = "These entities stay in the project libraries — only removed from this board. To delete one for good, use its right-click → Delete in the library.",
        ["Board_EmptyTitle"]      = "Boards are whiteboards",
        ["Board_EmptyBody"]       = "They're for sketching how objects, data types and classes relate to each other — but they're ignored during code generation.\n\nRight-click to add cards.",
        ["Code_DeletePerm"]       = "✕ Delete entity (permanent)",
        ["Code_DeletePermConfirm"]= "Permanently delete \"{0}\" from the project? This cannot be undone.",
        ["Code_DeleteEntityTitle"]= "Delete entity",
        ["Code_DeleteConnection"] = "✕ Delete connection",
        ["Code_AddReroute"]       = "◇ Insert reroute node here",
        ["Code_RemoveReroute"]    = "✕ Remove reroute node",
        ["Code_AddExisting"]      = "Add existing…",
        ["Code_AddExistingTitle"] = "Add existing entity",
        ["Code_AllOnBoard"]       = "Every entity is already on this board.",
        ["Code_AddEntityTitle"]   = "Add entity",
        ["Code_NewTypeTitle"]     = "New {0}",

        // Code exporter
        ["Export_Title"]    = "Export — {0}",
        ["Export_Language"] = "Language:",
        ["Export_Count"]    = "{0} entities",
        ["Export_Copy"]     = "📋 Copy",
        ["Export_Save"]     = "💾 Save…",
        ["Export_Close"]    = "Close",
        ["Export_Open"]     = "⇩ Open exporter",
        ["Export_Empty"]    = "No entities to export yet — add some in the structure sections first.",
        ["Export_Intro"]    = "Generate source skeletons from your structures in 10 languages. Function/method bodies come from their structograms where you've drawn them.",

        // App menu
        ["Menu_About"]      = "ℹ Info  (v{0})",
        ["Menu_AboutTitle"] = "About StructoFox",
        ["Menu_CloseProject"] = "Close project",
        ["Menu_Print"]        = "Print / Export…",
        ["Menu_Theme"]      = "🎨 Theme",
        ["Menu_Palette"]    = "Palette editor…",
        ["Home_RecentLabel"] = "Recent",
        ["Menu_Language"]   = "🌐 Language",
        ["Menu_Options"]    = "⚙ Options",
        ["Menu_Extensions"]   = "🧩 Extensions",
        ["Opt_NormWarn"]    = "Warn about non-DIN elements",
        ["Opt_NormMark"]    = "Mark non-DIN elements (N̶)",
        ["Opt_NormWarnTip"] = "Show a warning when a diagram uses elements that aren't DIN 66001/66261 compliant.",
        ["Opt_NormMarkTip"] = "Visually mark non-DIN elements in diagrams (a struck-through N badge).",
        ["Menu_DefaultHeaderTip"] = "Set the title-block/header applied automatically to new diagrams (name, project, author, date…).",
        ["Menu_UserInfoTip"] = "Your name and department — suggested into a new diagram's header.",
        ["Menu_BackupTip"]  = "Configure automatic project backups (folder, on-close backup, how many to keep).",
        ["Opt_SuppressTip"] = "Show this one-time info message again (unchecked = it stays hidden).",
        ["Opt_SubRemove"]   = "Subroutine-removal note",
        ["Opt_BoardRemove"] = "Board-removal note",
        ["Norm_AvoidDiagonal"] = "Diagonal arrows are allowed but should be avoided — use only in rare cases.",

        // Project context menu (home)
        ["Proj_Rename"]       = "✎ Rename…",
        ["Proj_RenamePrompt"] = "Project name:",
        ["Proj_OpenFolder"]   = "📂 Open folder",
        ["Proj_OpenCode"]     = "📂 Open Code folder",
    };

    // German overlay; any key not listed here quietly falls through to the English baseline.
    static readonly Dictionary<string, string> De = new()
    {
        // Entwürfe (Einzel-Diagramme ohne Projekt)
        ["Sketch_Nav"]      = "✏  Sketchbook",
        ["Sketch_NavTip"]   = "Einzel-Diagramme ohne Projekt (Ordner: Dokumente/StructoFox/Sketchbook)",
        ["Sketch_Title"]    = "Sketchbook",
        ["Sketch_NewPap"]   = "＋ 🔁 PAP",
        ["Sketch_NewStruct"] = "＋ ▦ Struktogramm",
        ["Sketch_NewBoard"] = "＋ 🗺 Board",
        ["Sketch_Empty"]    = "Noch keine Entwürfe — oben einen anlegen.",
        ["Sketch_NamePrompt"] = "Entwurf-Name:",
        ["Sketch_DeleteConfirm"] = "Entwurf “{0}” löschen? Das Diagramm wird mitgelöscht.",
        ["Sketch_TypeAll"]  = "Alle",
        ["Sketch_Open"]     = "📂 Im Editor öffnen",
        ["Sketch_OpenTip"]  = "Alle Entwürfe als Arbeitsbereich öffnen — zum Aufräumen von Klassen/Objekten, die auf einem Board entstanden sind",

        // Startseite / Projekt-Browser
        ["Home_NewProject"]    = "➕  Neues Projekt",
        ["Home_AddLibrary"]    = "📁  Bibliothek hinzufügen",
        ["Home_NewProjectTip"] = "Ein neues Projekt anlegen — ein Ordner mit Klassen, Funktionen, Diagrammen und Boards",
        ["Home_AddLibraryTip"] = "Einen Ordner registrieren, der mehrere Projekte enthält — ein Regal, das StructoFox durchsucht",
        ["Home_Recent"]        = "🕘  Zuletzt",
        ["Home_Libraries"]     = "Bibliotheken",
        ["Home_RemoveLibrary"] = "✕  Bibliothek entfernen",
        ["Home_NoProjects"]    = "Keine Projekte",
        ["Home_NoProjectsHint"] = "Noch keine Projekte hier — leg eins mit ➕ an",
        ["Home_TabProjects"]   = "📁  Projekte",

        // Cockpit / section chrome
        ["Sec_New"]         = "＋ Neu: {0}",
        ["Sec_NewPrompt"]   = "{0}-Name:",
        ["Sec_Empty"]       = "Noch keine {0}.",
        ["SecSg_Boards"] = "Board", ["SecSg_Main"] = "Main", ["SecSg_Namespace"] = "Namespace",
        ["SecSg_Class"] = "Klasse", ["SecSg_Struct"] = "Struct", ["SecSg_Interface"] = "Interface",
        ["SecSg_Enum"] = "Enum", ["SecSg_Function"] = "Funktion", ["SecSg_Object"] = "Objekt", ["SecSg_Export"] = "Export",
        ["SecPl_Boards"] = "Boards", ["SecPl_Main"] = "Main", ["SecPl_Namespace"] = "Namespaces",
        ["SecPl_Class"] = "Klassen", ["SecPl_Struct"] = "Structs", ["SecPl_Interface"] = "Interfaces",
        ["SecPl_Enum"] = "Enums", ["SecPl_Function"] = "Funktionen", ["SecPl_Object"] = "Objekte", ["SecPl_Export"] = "Export",

        ["Smoke_Header"]   = "Core-Rauchtest — aus einer Beispielklasse generiertes C#:",
        ["Diag_Title"]     = "Diagramm",
        ["Diag_SketchOf"]  = "Ablauf skizzieren von:\n{0}",
        ["Diag_PapExists"] = "🔁 Programmablaufplan (vorhanden)",
        ["Diag_Ns"]        = "▦ Struktogramm",
        ["Diag_NsExists"]  = "▦ Struktogramm (vorhanden)",
        ["Diag_NsTip"]     = "Nassi-Shneiderman-Struktogramm-Editor (DIN 66261)",
        ["Diag_Board"]     = "🗺 Board",

        // Common
        ["Common_Untitled"] = "Unbenannt",
        ["Flow_EditText"]   = "✎ Text bearbeiten…",

        // Main (entry point) tab
        ["Main_Blurb"]  = "Der Einstiegspunkt des Programms — die main(). Eine pro Projekt; sie bekommt einen eigenen Reiter, damit sie sichtbar bleibt.",
        ["Main_Create"] = "▶ Main anlegen",
        ["Main_Unset"]  = "Als Main entfernen",
        ["Main_SetAs"]  = "▶ Als Main setzen",

        // Structogram editor
        ["Struct_Title"]          = "▦  Struktogramm — {0}",
        ["Struct_Hint"]           = "Rechtsklick auf einen Block: bearbeiten / einfügen / umschließen. ＋ zum Hinzufügen.",
        ["Struct_CodeExport"]     = "⇩ Code-Skelett",
        ["Struct_CodeExportTip"]  = "Funktion/Methode dieses Struktogramms an den Code-Export schicken (nur Gerüst, ohne KI).",
        ["Struct_CodeNoEntity"]   = "Dieses Struktogramm gehört zu keiner Projekt-Funktion/-Methode — es gibt kein Code-Skelett zum Exportieren.",
        ["Struct_PhStatement"]    = "(Anweisung)",
        ["Struct_PhCondition"]    = "(Bedingung)",
        ["Struct_True"]           = "wahr",
        ["Struct_False"]          = "falsch",
        ["Struct_PhWhile"]        = "solange (…)",
        ["Struct_PhDoWhile"]      = "tue … solange (…)",
        ["Struct_KwWhile"]        = "solange",
        ["Struct_KwDoWhile"]      = "tue … solange",
        ["Struct_PhSelector"]     = "(Selektor)",
        ["Struct_Case"]           = "Fall",
        ["Struct_InsertAbove"]    = "Darüber einfügen",
        ["Struct_InsertBelow"]    = "Darunter einfügen",
        ["Struct_AddLoopBody"]    = "Zum Schleifenkörper hinzufügen",
        ["Struct_AddTrue"]        = "Zum WAHR-Zweig hinzufügen",
        ["Struct_AddFalse"]       = "Zum FALSCH-Zweig hinzufügen",
        ["Struct_AddArm"]         = "Fall-Zweig hinzufügen",
        ["Struct_DeleteBlock"]    = "✕ Block löschen",
        ["Struct_KStatement"]     = "Anweisung",
        ["Struct_KIf"]            = "Wenn / Sonst",
        ["Struct_KWhile"]         = "While-Schleife (kopfgesteuert)",
        ["Struct_KDoWhile"]       = "Do-While-Schleife (fußgesteuert)",
        ["Struct_KCase"]          = "Fallauswahl (mehrfach)",
        ["Struct_KSubroutine"]    = "Unterprogramm (verlinkt ein Diagramm)",
        ["Struct_PhSubroutine"]   = "(Unterprogramm)",
        ["Struct_DefSubroutine"]  = "Unterprogramm",
        ["Struct_KJump"]          = "Ausstieg (return / break / continue)",
        ["Struct_DefJump"]        = "return",
        ["Struct_ShowChart"]      = "🗺 Diagramm zeigen…",
        ["Struct_ShowChartTip"]   = "Doppelklick öffnet das Diagramm dieses Unterprogramms",
        ["Sub_NamePrompt"]        = "Unterprogramm-(Funktions-)Name:",
        ["Sub_LinkTitle"]         = "Unterprogramm verknüpfen",
        ["Sub_Namespace"]         = "Namespace (zum Auswählen / Anlegen):",
        ["Sub_CallForm"]          = "Aufruf (optional):",
        ["Sub_ReturnLabel"]       = "Rückgabe in:",
        ["Sub_ArgsLabel"]         = "Argumente:",
        ["Sub_AssignHint"]        = "Variable (z. B. ergebnis)",
        ["Sub_ArgsHint"]          = "Argumente (z. B. x, y)",
        ["Sub_Instance"]          = "Objekt, auf dem die Methode aufgerufen wird (nicht statisch):",
        ["Sub_InstanceHint"]      = "Instanz (z. B. meinObjekt)",
        ["Sub_NewObject"]         = "＋ Neues Objekt…",
        ["Sub_Link"]              = "🔗 Unterprogramm verknüpfen…",
        ["Sub_Relink"]            = "Neu verlinken (Ziel ändern)…",
        ["Sub_PickExisting"]      = "Vorhandene Funktion wählen",
        ["Sub_CreateNew"]         = "Neue Funktion anlegen:",
        ["Sub_DuplicateTitle"]    = "Funktion existiert bereits",
        ["Sub_DuplicateMsg"]      = "Eine Funktion mit diesem Namen existiert in diesem Namespace bereits.\n\nJa = die vorhandene verwenden,  Nein = trotzdem eine weitere anlegen,  Abbrechen = zurück.",
        ["Sec_DupMsg"]            = "Ein/e {0} mit dem Namen „{1}“ existiert in diesem Namespace bereits. Trotzdem eine weitere anlegen?",
        ["Sec_DupTitle"]          = "Name existiert bereits",
        ["Board_CrossDupMsg"]     = "Bereits in diesem Projekt vorhanden: {0}. Zuerst löschen oder umbenennen, dann erneut einfügen.",
        ["Usage_BaseClass"]       = "Basisklasse",
        ["Usage_Interface"]       = "Interface",
        ["Usage_InstanceOf"]      = "Instanz von",
        ["Usage_Namespace"]       = "Namespace",
        ["Usage_Board"]           = "Board",
        ["Usage_Subroutine"]      = "Unterprogramm",
        ["Usage_FieldType"]       = "Typ",
        ["Link_Title"]            = "Wird noch verwendet",
        ["Link_UsedByRename"]     = "Wird noch verwendet von:\n{0}\n\nWas soll mit diesen Verknüpfungen passieren?",
        ["Link_ActionRename"]     = "Verknüpfungen mit umbenennen",
        ["Link_ActionLeave"]      = "Verknüpfungen belassen (zeigen dann ins Leere)",
        ["Link_ActionDelete"]     = "Verknüpfungen löschen",
        ["Link_UsedByDelete"]     = "Wird noch verwendet von:{0}\n\nDiese Verknüpfungen werden entfernt.",
        ["Sub_RemoveInfo"]        = "Das Unterprogramm bleibt in der Functions-Bibliothek — entfernt wurde nur dieser Block/Knoten. Zum endgültigen Löschen im Functions-Reiter entfernen.",
        ["Struct_AddBlockTip"]    = "Einen Block hinzufügen",
        ["Struct_AddInline"]      = "＋ hinzufügen",
        ["Struct_PromptStatement"] = "Anweisung",
        ["Struct_PromptCondition"] = "Bedingung / Ausdruck",
        ["Struct_PromptCaseLabel"] = "Fall-Beschriftung",
        ["Struct_DefCondition"]   = "Bedingung",
        ["Struct_DefWhile"]       = "solange (Bedingung)",
        ["Struct_DefDoWhile"]     = "tue … solange (Bedingung)",
        ["Struct_DefSelector"]    = "Selektor",
        ["Struct_DefStatement"]   = "Anweisung",
        ["Struct_FlaggedTip"]     = "Dieser Bereich konnte nicht aus dem Ablaufplan strukturiert werden — bitte manuell prüfen und umschreiben.",

        // Flowchart (PAP) editor
        ["Common_ResetZoomTip"]        = "Zoom zurücksetzen",
        ["Flow_Title"]                 = "🔁  Ablauf — {0}",
        ["Flow_Start"]                 = "⬭ Start",
        ["Flow_OnlyOneStart"]          = "Ein Ablaufplan hat nur einen Start — er wird zu genau einer Funktion. Für einen weiteren Ablauf eine eigene Funktion/ein eigenes Diagramm anlegen.",
        ["Flow_Process"]               = "▭ Prozess",
        ["Flow_Decision"]              = "◇ Verzweigung",
        ["Flow_MultiDecision"]         = "◇ Multi-Verzweigung (switch/case)",
        ["Flow_CombDir"]               = "Kamm-Richtung",
        ["Flow_CombBottom"]            = "Unten (Zinken nach unten)",
        ["Flow_CombRight"]             = "Rechts (Zinken nach rechts)",
        ["Flow_CombBoth"]              = "Beide",
        ["Flow_TineSpacing"]           = "Zinkenabstand (Grid-Schritte)",
        ["Flow_AddTine"]               = "Fall (Zinke) hinzufügen",
        ["Flow_RemoveTine"]            = "Fall (Zinke) entfernen",
        ["Flow_ResetStem"]             = "Stamm zurücksetzen",
        ["Flow_CaseDefault"]           = "Fall",
        ["Flow_CaseLabelDup"]          = "Jeder Fall braucht eine eindeutige, nicht-leere Beschriftung.",
        ["Flow_IO"]                    = "▱ E/A",
        ["Flow_Subroutine"]            = "⊟ Unterprogramm",
        ["Flow_End"]                   = "⬭ Ende",
        ["Flow_Note"]                  = "✎ Text",
        ["Flow_Annotation"]            = "⌐ Bemerkung",
        ["Flow_MirrorAnnotation"]      = "Spiegeln (links/rechts)",
        ["Flow_Connector"]             = "◯ Konnektor",
        ["Flow_DefConnector"]          = "A",
        ["Flow_Junction"]              = "• Sammelpunkt",
        ["Flow_AddNodeTip"]            = "Einen {0}-Knoten hinzufügen",
        ["Flow_Select"]                = "🖐",
        ["Flow_SelectTip"]             = "Normalmodus: Knoten auswählen und ziehen (leeren Canvas ziehen = Rechteck-Auswahl; rechte Maustaste ziehen = verschieben)",
        ["Flow_Scale"]                 = "⤢",
        ["Flow_ScaleTip"]              = "Skalieren-Modus: an den Griffen eines Symbols ziehen, um es zu skalieren (bis zur Standardgröße)",
        ["Flow_Connect"]               = "→ Verbinden",
        ["Flow_ConnectTip"]            = "Klicke einen Knoten, dann einen anderen, um einen Pfeil zu ziehen",
        ["Flow_View"]                  = "⚙ Optionen ▾",
        ["Flow_ZoomTip"]               = "Zoom — Vorgaben oder Wert eingeben",
        ["Flow_ZoomManual"]            = "z. B. 130",
        ["Flow_ViewTip"]               = "Optionen: Farben, Dekoration, Zoom, Raster",
        ["Flow_LangLabel"]             = "Syntax:",
        ["Flow_LangTip"]               = "Code-Sprache für das Autocomplete im Knoten-Editor (Methodensignaturen werden in dieser Syntax gezeigt) — projektweite Einstellung.",
        ["View_Crop"]                  = "Canvas zuschneiden",
        ["View_CropTip"]               = "Canvas auf den Inhalt zuschneiden – leeren Raum oben/links entfernen",
        ["Grid_Header"]                = "Raster",
        ["Grid_Show"]                  = "Raster anzeigen",
        ["Grid_Snap"]                  = "Am Raster einrasten",
        ["Grid_Lines"]                 = "Linien",
        ["Grid_Dashed"]                = "Gestrichelt",
        ["Grid_Dots"]                  = "Punkte",
        ["Grid_Color"]                 = "🎨 Rasterfarbe…",
        ["Grid_Opacity"]               = "Raster-Deckkraft",
        ["Flow_Remove"]                = "🗑",
        ["Flow_RemoveTip"]             = "Klicke einen Knoten oder Pfeil, um ihn zu löschen",
        ["Flow_DefStart"]              = "Start",
        ["Flow_DefEnd"]                = "Ende",
        ["Flow_DefDecision"]           = "Bedingung?",
        ["Flow_DefIO"]                 = "Eingabe / Ausgabe",
        ["Flow_DefCall"]               = "Aufruf …",
        ["Flow_DefNote"]               = "Text",
        ["Flow_DefAnnotation"]         = "Bemerkung",
        ["Flow_DefStep"]               = "Schritt",
        ["Flow_DeleteNode"]            = "✕ Knoten löschen",
        ["Flow_NodeTextPrompt"]        = "Knotentext",
        ["Flow_BranchPrompt"]          = "Zweig-Beschriftung (z.B. ja / nein)",
        ["Flow_ArrowPrompt"]           = "Pfeil-Beschriftung",
        ["Flow_EditLabel"]             = "✎ Beschriftung bearbeiten…",
        ["Flow_DeleteArrow"]           = "✕ Pfeil löschen",
        ["Flow_FlipArrow"]             = "⇄ Pfeilrichtung umkehren",
        ["Flow_StyleLine"]             = "─ Stil: Linie (ohne Pfeil)",
        ["Flow_StyleArrow"]            = "➤ Stil: Pfeil",
        ["Flow_Crossover"]             = "Crossover-Brücken (normwidrig)",
        ["Flow_CrossoverHint"]         = "Normwidrig: dient nur zur Markierung, ist temporär. Wird nicht gespeichert und beim nächsten Laden nicht mehr gezeigt.",
        ["Flow_ResetRoute"]            = "↺ Linienführung zurücksetzen",
        ["Flow_DetachJunction"]        = "⊘ Aus der Linie lösen",
        ["Flow_Transmission"]          = "⚡ Zu Übertragungsweg machen",
        ["Flow_TransmissionOff"]       = "⚡ Zurück zur normalen Flusslinie",
        ["Flow_ToStructogramTip"]      = "Diesen Programmablaufplan in ein Struktogramm umwandeln",
        ["Flow_ToStructogramTitle"]    = "In Struktogramm umwandeln",
        ["Flow_ToStructogramOverwrite"] = "Für diese Funktion existiert bereits ein Struktogramm. Mit dem umgewandelten Ablaufplan überschreiben?",
        ["Flow_ToStructogramExists"]    = "Für diesen Ablaufplan existiert bereits ein Struktogramm. Überschreiben oder das vorhandene öffnen?",
        ["Flow_ToStructogramOpen"]      = "Vorhandenes öffnen",
        ["Flow_ToStructogramOverwriteBtn"] = "Überschreiben",
        ["Flow_ToStructogramPartial"]  = "Einige Teile des Ablaufplans lassen sich nicht als Struktogramm ausdrücken (z. B. willkürliche Sprünge / Schleifen). Die zu überarbeitenden Knoten sind im Ablaufplan orange markiert. Strukturiere sie um und wandle dann erneut um.",
        ["Flow_ToStructogramNodeTip"]  = "Dieser Knoten ließ sich nicht ins Struktogramm strukturieren — den Ablauf hier umbauen.",
        ["Flow_Background"]            = "🎨 Hintergrundfarbe…",
        ["Flow_ArrowColor"]            = "🎨 Pfeilfarbe…",
        ["Flow_Colors"]                = "Farben",
        ["Flow_LinesOrtho"]           = "⌐ Linien: orthogonal",
        ["Flow_LinesDiagonal"]        = "⟍ Linien: diagonal",
        ["Flow_LinesTip"]             = "Zwischen DIN-orthogonalen Flusslinien und direkten Diagonalpfeilen wechseln",
        ["Flow_Symbol"]               = "DIN-Symbol",
        ["Flow_SymAuto"]              = "▱ Standard (Ein-/Ausgabe)",
        ["Flow_SymDocument"]          = "📄 Dokument (Ausdruck)",
        ["Flow_SymDisplay"]           = "🖥 Anzeige",
        ["Flow_SymManualInput"]       = "⌨ Handeingabe",
        ["Flow_SymPunchedCard"]       = "🗒 Lochkarte",
        ["Flow_SymMagneticTape"]      = "🎞 Magnetband",
        ["Flow_SymMagneticDisk"]      = "🛢 Magnetplatte / Datenbank",
        ["Flow_SymStoredData"]        = "🗄 Gespeicherte Daten",
        ["Flow_SymOffPage"]           = "⬠ Verbindung (Folgeseite)",
        ["Flow_PageWord"]             = "Seite",
        ["Flow_PageOf"]               = "Seite {0}/{1}",
        ["Flow_PagePrev"]             = "Vorherige Seite",
        ["Flow_PageNext"]             = "Nächste Seite",
        ["Flow_EntryReadOnly"]        = "Das ist der Einstieg auf der Folgeseite — seine Beschriftung spiegelt den Folgeseite-Knoten und ist hier nicht editierbar. Zum Ändern den Knoten auf der ersten Seite doppelklicken.",
        ["Flow_OffPageDup"]           = "Diese Folgeseiten-Beschriftung ist bereits vergeben. Jede muss eindeutig sein.",
        ["Flow_SymPreparation"]       = "⬡ Vorbereitung (Init / Schleife)",
        ["Flow_SymManualOperation"]   = "⏢ Manuelle Operation",
        ["Flow_SymLoopLimit"]         = "⌂ Schleifengrenze",
        ["Flow_SymDelay"]             = "⏱ Verzögerung",
        ["Flow_SymParallel"]          = "‖ Parallelmodus",
        ["Flow_SymSort"]              = "⬙ Sortieren",
        ["Flow_SymMerge"]             = "▽ Mischen",
        ["Flow_SymExtract"]           = "△ Extrahieren",
        ["Flow_SymCollate"]           = "⧖ Zusammenführen",
        ["Flow_SymCloud"]             = "☁ Cloud-Speicher",
        ["Flow_CatData"]              = "⛁ Daten",
        ["Flow_ExtOff"]               = "(erweiterte ISO-Symbole aus)",
        ["Flow_ExtIso"]               = "Erweiterte ISO-Symbole",
        ["Flow_ExtOutsideSet"]        = "Außerhalb des gewählten Symbolsatzes (dennoch ISO 5807)",
        ["Flow_CatStartEnd"]          = "⬭ Start / Ende",
        ["Flow_CatProcess"]           = "▭ Prozess",
        ["Flow_CatIO"]                = "▱ E/A",
        ["Flow_CatConnect"]           = "🔗 Verbinder",
        ["Flow_CatTip"]               = "Zum Wählen einer Variante mit der Maus drüberfahren",
        ["Flow_ArrowDin"]             = "➜ Pfeil (DIN, orthogonal)",
        ["Flow_ArrowFree"]            = "⟍ Pfeil (frei, schräg)",
        ["NodeTxt_Title"]              = "Knotentext",
        ["NodeTxt_Font"]               = "Schriftart",
        ["NodeTxt_Size"]               = "Größe",
        ["NodeTxt_Bold"]               = "Fett",
        ["NodeTxt_Italic"]             = "Kursiv",
        ["NodeTxt_Underline"]          = "Unterstrichen",
        ["NodeTxt_Strike"]             = "Durchgestrichen",

        // Diagramm-Deko (Titel / Wasserzeichen / Logo)
        ["Decor_Title"]      = "Header",
        ["Decor_Open"]       = "🏷 Header…",
        ["Decor_OpenTip"]    = "Titel, Info-Feld, Wasserzeichen und Logo auf dem Plan",
        ["Decor_TitleText"]  = "Titel:",
        ["Decor_ShowTitle"]  = "Titel auf dem Plan anzeigen",
        ["Decor_TitlePos"]   = "Position:",
        ["Decor_TitleSize"]  = "Größe:",
        ["Decor_TitleBold"]  = "Fett",
        ["Decor_TitleColor"] = "Titelfarbe",
        ["Decor_TitleEditTip"] = "Rechtsklick: Titel-Eigenschaften bearbeiten",
        ["Decor_WmAngle"]    = "Wasserzeichen-Winkel (°):",
        ["Decor_Watermark"]  = "Wasserzeichen (blasser diagonaler Text):",
        ["Decor_WatermarkImg"] = "Wasserzeichen-Bild (blass, zentriert):",
        ["Decor_Logo"]       = "Logo-Bild:",
        ["Decor_Browse"]     = "Durchsuchen…",
        ["Decor_ClearLogo"]  = "Leeren",
        ["Decor_FromPap"]    = "⤵ Header vom PAP holen",
        ["Decor_SaveTemplate"]   = "💾 Als Vorlage speichern…",
        ["Decor_ApplyTemplate"]  = "📋 Vorlage anwenden…",
        ["Decor_DeleteTemplate"] = "Löschen",
        ["Decor_TemplateName"]   = "Vorlagenname:",
        ["Decor_TemplateExists"] = "Eine Vorlage „{0}“ existiert bereits.\n\nÜberschreiben?",
        ["Decor_TemplatePick"]   = "Header-Vorlagen",

        // Druck- / Export-Composer
        ["Common_Ok"]            = "OK",
        ["Pc_GridBtn"]           = "▦ Raster ▾",
        ["Pc_GridShow"]          = "Raster anzeigen",
        ["Pc_GridSnap"]          = "Am Raster einrasten",
        ["Pc_GridSpacing"]       = "Abstand",
        ["Pc_GridColor"]         = "Farbe",
        ["Pc_GridOpacity"]       = "Deckkraft (%)",
        ["Pc_GridWidth"]         = "Linienbreite",
        ["Pc_GridStyle"]         = "Linienart",
        ["Pc_StyleSolid"]        = "Durchgezogen",
        ["Pc_StyleDotted"]       = "Gepunktet",
        ["Pc_StyleDashed"]       = "Gestrichelt",
        ["Pc_StyleCrosses"]      = "Kreuze",
        ["Pc_StyleCrossesDots"]  = "Kreuze + Punkte",
        ["Pc_StyleCrossesDashes"]= "Kreuze + Striche",
        ["Pc_TextBox"]           = "Textfeld",
        ["Pc_Label"]             = "Beschriftung",
        ["Pc_Size"]              = "Größe",
        ["Pc_ColorText"]         = "Text",
        ["Pc_Background"]        = "Hintergrund",
        ["Pc_Border"]            = "Rahmen",
        ["Pc_BorderWidth"]       = "Rahmenbreite",
        ["Pc_Editor"]            = "Editor",
        ["Pc_Align"]             = "Ausrichtung",
        ["Pc_AlignLeft"]         = "Links",
        ["Pc_AlignCenter"]       = "Zentriert",
        ["Pc_AlignRight"]        = "Rechts",
        ["Pc_Default"]           = "(Standard)",
        ["Pc_ListHint"]          = "Liste: 1. / a) / - / * am Zeilenanfang tippen — Unterebenen mit führenden Leerzeichen einrücken.",
        ["Pc_Preview"]           = "Vorschau",
        ["Pc_LineSpacing"]       = "Zeilenabstand",
        ["Pc_Marker"]            = "Marker",
        ["Pc_ApplySize"]         = "Größe ↵",
        ["Pc_SelSize"]           = "Schriftgröße der Markierung",
        ["Pc_ClearFormat"]       = "Formatierung der Markierung entfernen",
        ["Pc_FormatHelp"]        = "Formatierung — Text markieren, dann anwenden:  B fett · I kursiv · U unterstrichen · S durchgestrichen · x² hochgestellt · x₂ tiefgestellt · A Textfarbe · ▨ Marker · Größe = Schriftgröße nur für die Markierung · ⊘ Formatierung entfernen.\nListen: 1. / a) / - / * am Zeilenanfang tippen; Unterebenen mit führenden Leerzeichen einrücken.\nSchriftart, Ausrichtung und Zeilenabstand gelten für die ganze Box.",
        ["Pc_AddText"]           = "＋ Text ▾",
        ["Pc_LabelSingle"]       = "Beschriftung (einzeilig)",
        ["Pc_TextMulti"]         = "Textfeld (mehrzeilig)",
        ["Pc_AddHeader"]         = "＋ Header",
        ["Pc_MenuFile"]          = "📁 Datei ▾",
        ["Pc_MenuOptions"]       = "⚙ Optionen ▾",
        ["Pc_Save"]              = "💾 Speichern",
        ["Pc_Load"]              = "Laden…",
        ["Pc_NewDoc"]            = "Neues Dokument",
        ["Pc_Rename"]            = "Umbenennen…",
        ["Pc_SaveAs"]            = "Speichern unter…",
        ["Pc_OverwriteConfirm"]  = "Ein Dokument „{0}“ existiert bereits.\n\nÜberschreiben?",
        ["Pc_PaperFormat"]       = "Papierformat…",
        ["Pc_GridSettings"]      = "Raster…",
        ["Pc_InsertHeader"]      = "Header",
        ["Pc_Paper"]             = "Papier",
        ["Pc_Orientation"]       = "Ausrichtung",
        ["Pc_Portrait"]          = "Hochformat",
        ["Pc_Landscape"]         = "Querformat",
        ["Pc_Name"]              = "Name",
        ["Pc_LoadTitle"]         = "Dokument laden",
        ["Pc_NoSaved"]           = "Noch keine gespeicherten Dokumente.",
        ["Pc_Delete"]            = "Löschen",
        ["Pc_DeleteConfirm"]     = "„{0}“ löschen?",
        ["Pc_OpenFolder"]        = "📁 Ordner öffnen",
        ["Pc_Margins"]           = "Ränder (cm)",
        ["Pc_MTop"]              = "Oben",
        ["Pc_MBottom"]           = "Unten",
        ["Pc_MLeft"]             = "Links",
        ["Pc_MRight"]            = "Rechts",
        ["Pc_HeaderWidth"]       = "Header-Breite…",
        ["Pc_HeaderWidthTitle"]  = "Header-Maximalbreite",
        ["Pc_WidthCm"]           = "Maximalbreite (cm)",
        ["Pc_ToDefault"]         = "Auf Standard",
        ["Pc_ShowPageNumber"]    = "Seitenzahl anzeigen",
        ["Pc_ExportPng"]         = "Exportieren…",
        ["Pc_ExportTitle"]       = "Export",
        ["Pc_ExportDpi"]         = "Auflösung (DPI)",
        ["Pc_ExportFormat"]      = "Format",
        ["Pc_FmtPngPages"]       = "PNG (eine Datei pro Seite)",
        ["Pc_FmtTiffPages"]      = "TIFF (eine Datei pro Seite)",
        ["Pc_FmtTiffMulti"]      = "TIFF (mehrseitig)",
        ["Pc_FmtPdf"]            = "PDF",
        ["ImgExport_Menu"]       = "🖼 Als Bild exportieren…",
        ["ImgExport_Tip"]        = "Dieses Diagramm (wie angezeigt) als einzelnes Bild exportieren (PNG/JPG/BMP/TIFF).",
        ["ImgExport_Title"]      = "Bild-Export",
        ["ImgExport_Empty"]      = "Noch nichts zu exportieren.",
        ["Pc_Exported"]          = "{0} Seite(n) exportiert",
        ["Pc_ExportFailed"]      = "Export fehlgeschlagen:",
        ["Pc_Saved"]             = "Gespeichert",
        ["Pc_Edit"]              = "Bearbeiten…",
        ["Pc_Bigger"]            = "Größer",
        ["Pc_Smaller"]           = "Kleiner",
        ["Pc_ScaleDots"]         = "Skalieren…",
        ["Pc_ResetSize"]         = "Größe zurücksetzen (100 %)",
        ["Pc_Update"]            = "Aktualisieren",
        ["Pc_EditSource"]        = "Quelle bearbeiten",
        ["Pc_Delete"]            = "Löschen",
        ["Pc_ScalePrompt"]       = "Skalierung (%) — 100 = Original",
        ["Pc_ScaleTitle"]        = "Skalieren",
        ["Pc_NoDiagrams"]        = "Keine Diagramme gefunden — zeichne zuerst einen Ablaufplan",
        ["Pc_AddDiagramTitle"]   = "Diagramm hinzufügen",
        ["Pc_HeaderEmpty"]       = "Kopf ist leer — Titel, Infofeld oder Logo aktivieren",
        ["Pc_NothingToRender"]   = "(nichts zu rendern)",
        ["Menu_DefaultHeader"]   = "🏷 Standard-Header…",
        ["Menu_UserInfo"]        = "👤 Benutzerdaten…",
        ["Menu_Backup"]          = "💾 Backup…",
        ["Backup_Title"]         = "Projekt-Backup",
        ["Backup_Folder"]        = "Backup-Ordner (jedes Projekt bekommt einen Unterordner):",
        ["Backup_Browse"]        = "Durchsuchen…",
        ["Backup_PickFolder"]    = "Backup-Ordner wählen",
        ["Backup_OnClose"]       = "Automatisches Backup beim Schließen eines Projekts",
        ["Backup_Keep"]          = "Anzahl aufbewahrter Backups pro Projekt:",
        ["Backup_Note"]          = "Beim Schließen wird — falls sich das Projekt seit dem letzten Backup geändert hat — eine .zip des ganzen Projekts nach <Backup-Ordner>/<Projekt>/ geschrieben. Es werden nur die neuesten N Zips behalten; ältere werden gelöscht.",
        ["Backup_ErrTitle"]      = "Backup",
        ["Backup_ErrIsProject"]  = "Dieser Ordner ist ein StructoFox-Projekt. Bitte wähle einen Backup-Ordner, der KEIN Projekt ist (und nicht in einem liegt) — sonst kann kein Backup erstellt werden.",
        ["Backup_ErrInside"]     = "Der Backup-Ordner liegt innerhalb des zu sichernden Projekts, deshalb wurde kein Backup erstellt. Bitte wähle einen Backup-Ordner außerhalb des Projekts.",
        ["Backup_ErrFailed"]     = "Das Backup konnte nicht geschrieben werden nach:\n{0}\n\nBitte prüfe, ob der Ordner existiert und beschreibbar ist.",
        ["UserInfo_Title"]       = "Benutzerdaten",
        ["UserInfo_Name"]        = "Name (wird als Ersteller im Header vorgeschlagen):",
        ["UserInfo_Dept"]        = "Abteilung (wird im Header vorgeschlagen):",
        ["Decor_Today"]          = "Heute",
        ["DefHdr_Title"]         = "Standard-Header für neue Diagramme",
        ["DefHdr_Pap"]           = "Neue Ablaufpläne (PAP):",
        ["DefHdr_Struct"]        = "Neue Struktogramme:",
        ["DefHdr_None"]          = "(keiner)",
        ["Decor_Corner"]     = "Logo-Position:",
        ["Decor_LogoWidth"]  = "Logo-Breite:",
        ["Decor_InfoSection"]  = "Info-Feld (Schriftfeld)",
        ["Decor_ShowInfo"]     = "Info-Feld auf dem Plan anzeigen",
        ["Decor_ShowPage"]     = "Seitenzahl anzeigen (automatisch, im Info-Feld)",
        ["Decor_InfoPos"]      = "Info-Position:",
        ["Decor_InfoName"]     = "Name:",
        ["Decor_InfoProject"]  = "Projekt:",
        ["Decor_InfoProjectNo"]= "Projekt-Nr.:",
        ["Decor_InfoVersion"]  = "Version:",
        ["Decor_InfoDate"]     = "Datum:",
        ["Decor_InfoAuthor"]   = "Ersteller:",
        ["Decor_InfoDept"]     = "Abteilung:",
        ["Decor_InfoExtra"]    = "Notiz:",
        ["Decor_InfoPage"]     = "Seite:",

        // Per-element styling
        ["Style_Menu"]      = "🎨 Stil",
        ["Style_Line"]      = "Linienfarbe",
        ["Style_Fill"]      = "Füllfarbe",
        ["Style_Text"]      = "Textfarbe",
        ["Style_Thickness"] = "Linienstärke",
        ["Style_Reset"]     = "Stil zurücksetzen",
        ["Style_Inherit"]   = "Erben (Standard)",
        ["Style_Open"]      = "🎨 Stil…",
        ["Palette_Choose"]  = "Palette wählen",
        ["Pal_Title"]         = "🎨 Palette-Editor",
        ["Pal_Label"]         = "Palette:",
        ["Pal_New"]           = "Neu…",
        ["Pal_NewTip"]        = "Eine neue Palette erstellen",
        ["Pal_Save"]          = "💾 Speichern",
        ["Pal_SaveTip"]       = "Diese Palette in eine Datei speichern",
        ["Pal_AddUpdate"]     = "＋ Hinzufügen / Aktualisieren",
        ["Pal_AddUpdateTip"]  = "Eine neue Farbe hinzufügen oder die ausgewählte aktualisieren",
        ["Pal_Remove"]        = "✕ Entfernen",
        ["Pal_RemoveTip"]     = "Ausgewählte Farbe entfernen",
        ["Pal_Name"]          = "Name:",
        ["Pal_ColorName"]     = "Farbname",
        ["Pal_DefaultColor"]  = "Farbe",
        ["Pal_NewPrompt"]     = "Name der neuen Palette:",
        ["Pal_NewDefault"]    = "Meine Palette",
        ["Pal_NewTitle"]      = "Neue Palette",
        ["Pal_Saved"]         = "Palette \"{0}\" gespeichert unter:\n{1}",
        ["Pal_SavedTitle"]    = "Palette gespeichert",

        // Style editor window
        ["StyleEd_Title"]     = "🎨 Element-Stil",
        ["StyleEd_Preset"]    = "Stil-Slot:",
        ["StyleEd_Apply"]     = "Anwenden",
        ["StyleEd_SaveSlot"]  = "💾 Als Slot speichern…",
        ["StyleEd_Line"]      = "Linienfarbe",
        ["StyleEd_Fill"]      = "Füllfarbe",
        ["StyleEd_Text"]      = "Textfarbe",
        ["StyleEd_Thickness"] = "Linienstärke",
        ["StyleEd_Preview"]   = "Vorschau",
        ["StyleEd_Sample"]    = "Beispieltext",
        ["StyleEd_SlotName"]  = "Slot-Name:",
        ["Common_OK"]         = "OK",
        ["Common_Cancel"]     = "Abbrechen",
        ["Common_Yes"]        = "Ja",
        ["Common_No"]         = "Nein",
        ["Common_DontShowAgain"] = "Nicht wieder anzeigen",
        ["NewProj_ExistsTitle"] = "Name existiert bereits",
        ["NewProj_ExistsMsg"]   = "Ein Projekt „{0}“ existiert in dieser Bibliothek bereits.\n\nJa = öffnen,  Nein = anderen Namen wählen,  Abbrechen = abbrechen.",

        // Entity editor dialog
        ["Common_Name"]            = "Name",
        ["Common_None"]            = "(keine)",
        ["Common_Save"]            = "Speichern",
        ["Common_AddPlus"]         = "＋ Hinzufügen",
        ["CodeEdit_Title"]         = "{0} bearbeiten",
        ["CodeEdit_Type"]          = "Typ",
        ["CodeEdit_Namespace"]     = "Namespace",
        ["CodeEdit_ParentNamespace"] = "Übergeordneter Namespace",
        ["CodeEdit_Description"]   = "Beschreibung",
        ["CodeEdit_Inherits"]      = "Erbt von",
        ["CodeEdit_Implements"]    = "Implementiert",
        ["CodeEdit_NoInterfaces"]  = "(noch keine Interfaces definiert)",
        ["CodeEdit_InstanceOf"]    = "Instanz von",
        ["CodeEdit_ObjectUsage"]   = "Verwendung (aus Diagrammen ermittelt)",
        ["CodeEdit_ObjCreated"]    = "Erstellt in:",
        ["CodeEdit_ObjDestroyed"]  = "Vernichtet in:",
        ["CodeEdit_ObjUsed"]       = "Verwendet in:",
        ["CodeEdit_Methods"]       = "Methoden",
        ["CodeEdit_Fields"]        = "Felder",
        ["CodeEdit_EnumValues"]    = "Enum-Werte",
        ["CodeEdit_DataPorts"]     = "Datenports",
        ["CodeEdit_DeclaredVars"]  = "Deklarierte Variablen",
        ["CodeEdit_LoopVars"]      = "Schleifenvariablen",
        ["CodeEdit_VarsHint"]      = "Keine Variablen deklariert. Im Diagramm als eigenen Schritt notieren, z. B.  int summe = 0",
        ["CodeEdit_ConstructorLbl"]= "Konstruktor",
        ["CodeEdit_DestructorLbl"] = "Destruktor",
        ["CodeEdit_MethodFlowTip"] = "Ablauf / Struktogramm dieser Methode skizzieren",
        ["CodeEdit_AddParam"]      = "＋ Parameter",
        ["CodeEdit_AddMethod"]     = "Methode",
        ["CodeEdit_AddConstructor"]= "Konstruktor",
        ["CodeEdit_AddDestructor"] = "Destruktor",
        ["CodeEdit_AddGetter"]     = "Getter hinzufügen (Get…)",
        ["CodeEdit_AddSetter"]     = "Setter hinzufügen (Set…)",
        ["CodeEdit_DefaultValue"]  = "Wert",
        ["CodeEdit_Delete"]        = "✕  Löschen",
        ["CodeEdit_DeleteConfirm"] = "„{0}“ löschen? Alles, was daran hängt (Parameter, Diagramme, …), geht mit.",
        ["CodeEdit_DeleteTitle"]   = "Löschen",
        ["CodeEdit_DeleteBoardWarn"] = "Dieser Methode ist ein Board zugewiesen ({0}). Es wird NICHT gelöscht — bitte manuell im Boards-Reiter entfernen.",
        ["Common_NameColon"]       = "Name:",
        ["Common_Add"]             = "Hinzufügen",

        // Boards-Galerie (Cockpit-Sektion)
        ["Boards_New"]        = "＋ Neues Board",
        ["Boards_NewPrompt"]  = "Board-Name:",
        ["Boards_Default"]    = "Board",
        ["Boards_Empty"]      = "Noch keine Boards — mit ＋ eines anlegen.",
        ["Boards_Open"]       = "Öffnen",
        ["Boards_Rename"]     = "✎ Umbenennen…",
        ["Boards_Delete"]     = "✕  Board löschen",
        ["Boards_DeleteConfirm"] = "Board „{0}“ löschen? (Entities bleiben; nur das Layout dieses Boards wird entfernt.)",
        ["Boards_DeleteTitle"]   = "Board löschen",

        // Code-Board-Leinwand
        ["Code_AddToBoard"]       = "＋ Hinzufügen",
        ["Code_AddToBoardTip"]    = "Eine neue oder vorhandene Entity zu diesem Board hinzufügen",
        ["Code_AllTypes"]         = "(alle Typen)",
        ["Code_SelectMode"]       = "✋ Auswählen / Verschieben",
        ["Code_SelectModeTip"]    = "Karten auswählen & verschieben: auf leere Fläche ziehen = Rahmenauswahl, Rechts-Ziehen = Canvas verschieben, Strg+Klick = hinzu/abwählen, Strg+A = alle, Entf = entfernen",
        ["Code_ConnectPorts"]     = "→ Ports verbinden",
        ["Code_ScaleCards"]       = "⤢ Skalieren",
        ["Code_ScaleCardsTip"]    = "Skalieren-Modus: an den Griffen einer Karte ziehen, um sie zu skalieren (bis zur natürlichen Größe)",
        ["Code_ConnectPortsTip"]  = "Erst einen Ausgangs-Port, dann einen passenden Eingangs-Port klicken",
        ["Code_RemoveCards"]      = "✕ Vom Board entfernen",
        ["Code_RemoveCardsTip"]   = "Ausgewählte Karten vom Board entfernen (Entities bleiben erhalten)",
        ["Code_ExportAll"]        = "⇩ Alle exportieren",
        ["Code_ExportAllTip"]     = "Quellcode für jede Entity auf diesem Board erzeugen",
        ["Code_ExportSelected"]   = "⇩ Auswahl exportieren",
        ["Code_ExportSelectedTip"]= "Quellcode für die ausgewählten Entities erzeugen",
        ["Code_NoSelection"]      = "Nichts ausgewählt.",
        ["Code_ConnStartOutput"]  = "Eine Verbindung beginnt an einem Ausgangs-Port (rechte Seite).",
        ["Code_ConnEndInput"]     = "Eine Verbindung endet an einem Eingangs-Port (linke Seite).",
        ["Code_ConnTitle"]        = "Ports verbinden",
        ["Code_MismatchConv"]     = "Übergabekonvention passt nicht: {0} ist {1}, aber {2} ist {3}.",
        ["Code_MismatchType"]     = "Typ passt nicht: {0} ist {1}, aber {2} ist {3}.",
        ["Code_MismatchTitle"]    = "Verbindung nicht möglich",
        ["Code_AddType"]          = "{0} hinzufügen…",
        ["Code_Edit"]             = "✎ Bearbeiten…",
        ["Code_SketchFlow"]       = "🔁 Ablauf skizzieren…",
        ["Code_ExportThis"]       = "⇩ Diese exportieren",
        ["Code_SwitchVertical"]   = "Ports: auf vertikal umstellen",
        ["Code_SwitchHorizontal"] = "Ports: auf horizontal umstellen",
        ["Code_RemoveFromBoard"]  = "Vom Board entfernen",
        ["Board_RemoveInfo"]      = "Diese Entities bleiben in den Projekt-Bibliotheken — nur vom Board entfernt. Zum endgültigen Löschen in der Bibliothek per Rechtsklick → Löschen.",
        ["Board_EmptyTitle"]      = "Boards sind Whiteboards",
        ["Board_EmptyBody"]       = "Sie dienen dazu, die Beziehungen von Objekten, Datentypen und Klassen untereinander darzustellen — bei der Codegenerierung werden sie aber ignoriert.\n\nRechtsklick, um Karten hinzuzufügen.",
        ["Code_DeletePerm"]       = "✕ Entity löschen (dauerhaft)",
        ["Code_DeletePermConfirm"]= "„{0}“ dauerhaft aus dem Projekt löschen? Das kann nicht rückgängig gemacht werden.",
        ["Code_DeleteEntityTitle"]= "Entity löschen",
        ["Code_DeleteConnection"] = "✕ Verbindung löschen",
        ["Code_AddReroute"]       = "◇ Reroute-Node hier einfügen",
        ["Code_RemoveReroute"]    = "✕ Reroute-Node entfernen",
        ["Code_AddExisting"]      = "Vorhandene hinzufügen…",
        ["Code_AddExistingTitle"] = "Vorhandene Entity hinzufügen",
        ["Code_AllOnBoard"]       = "Alle Entities sind bereits auf diesem Board.",
        ["Code_AddEntityTitle"]   = "Entity hinzufügen",
        ["Code_NewTypeTitle"]     = "Neue(s) {0}",

        // Code-Export
        ["Export_Title"]    = "Export — {0}",
        ["Export_Language"] = "Sprache:",
        ["Export_Count"]    = "{0} Entities",
        ["Export_Copy"]     = "📋 Kopieren",
        ["Export_Save"]     = "💾 Speichern…",
        ["Export_Close"]    = "Schließen",
        ["Export_Open"]     = "⇩ Exporter öffnen",
        ["Export_Empty"]    = "Noch nichts zu exportieren — lege zuerst in den Struktur-Sektionen etwas an.",
        ["Export_Intro"]    = "Erzeuge Quellcode-Gerüste aus deinen Strukturen in 10 Sprachen. Funktions-/Methodenrümpfe stammen aus den jeweiligen Struktogrammen, wo du sie gezeichnet hast.",

        // App-Menü
        ["Menu_About"]      = "ℹ Info  (v{0})",
        ["Menu_AboutTitle"] = "Über StructoFox",
        ["Menu_CloseProject"] = "Projekt schließen",
        ["Menu_Print"]        = "Drucken / Export…",
        ["Menu_Theme"]      = "🎨 Theme",
        ["Menu_Palette"]    = "Palette-Editor…",
        ["Home_RecentLabel"] = "Zuletzt",
        ["Menu_Language"]   = "🌐 Sprache",
        ["Menu_Options"]    = "⚙ Optionen",
        ["Menu_Extensions"]   = "🧩 Erweiterungen",
        ["Opt_NormWarn"]    = "Meldung wenn nicht normgerecht",
        ["Opt_NormMark"]    = "Markierung wenn nicht normgerecht (N̶)",
        ["Opt_NormWarnTip"] = "Warnt, wenn ein Diagramm Elemente nutzt, die nicht DIN 66001/66261 entsprechen.",
        ["Opt_NormMarkTip"] = "Markiert nicht-DIN-Elemente im Diagramm sichtbar (durchgestrichenes N).",
        ["Menu_DefaultHeaderTip"] = "Legt den Titel-/Header-Block fest, der neuen Diagrammen automatisch zugewiesen wird (Name, Projekt, Autor, Datum…).",
        ["Menu_UserInfoTip"] = "Dein Name und deine Abteilung — werden im Header neuer Diagramme vorgeschlagen.",
        ["Menu_BackupTip"]  = "Automatische Projekt-Backups einstellen (Ordner, Backup beim Schließen, Anzahl behaltener Backups).",
        ["Opt_SuppressTip"] = "Diese einmalige Hinweismeldung wieder anzeigen (nicht angehakt = bleibt versteckt).",
        ["Opt_SubRemove"]   = "Hinweis: Unterprogramm entfernen",
        ["Opt_BoardRemove"] = "Hinweis: vom Board entfernen",
        ["Norm_AvoidDiagonal"] = "Schräge Pfeile sind zulässig, sollten aber vermieden werden — nur in Ausnahmefällen einsetzen.",

        // Projekt-Kontextmenü (Home)
        ["Proj_Rename"]       = "✎ Umbenennen…",
        ["Proj_RenamePrompt"] = "Projektname:",
        ["Proj_OpenFolder"]   = "📂 Ordner öffnen",
        ["Proj_OpenCode"]     = "📂 Code-Ordner öffnen",
    };

    // Language code -> its string table. Lookups consult the active table, then English.
    static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
    {
        ["en"] = En,
        ["de"] = De,
    };

    /// <summary>
    /// Resolves a UI string by key for the active language.
    /// Falls back to English, then to the raw key itself — so a missing string shouts, it doesn't vanish.
    /// </summary>
    public static string S(string key)
    {
        if (_overlay.TryGetValue(key, out var ov)) return ov;
        if (Tables.TryGetValue(Lang, out var t) && t.TryGetValue(key, out var v)) return v;
        if (En.TryGetValue(key, out var en)) return en;
        return key;
    }
}
